"""Constants for SmplWise HA Dashboard."""

DOMAIN = "smplwise_ha_dashboard"
PANEL_URL = "smplwise-ha-dashboard"
PANEL_TITLE = "SmplWise"
PANEL_ICON = "mdi:home-lightning-bolt-outline"
FRONTEND_URL = "/smplwise-ha-dashboard/smplwise-ha-dashboard-v0.16.0.js"
STORAGE_KEY = "smplwise_ha_dashboard.config"
STORAGE_VERSION = 1

DEFAULT_CONFIG = {
    "config_schema_version": 8,
    "language": "auto",
    "theme": "smplwise",
    "default_view": "home",
    "camera_grid_count": 4,
    "text_scale": 1.0,
    "icon_scale": 1.0,
    "entity_card_shape": "rectangle",
    "entity_card_height": 158,
    "category_settings": {},
    "home_info": {
        "show_weather": True,
        "weather_entity_id": None,
        "show_parasha": False,
        "parasha_entity_id": None,
        "show_shabbat": False,
        "candle_lighting_entity_id": None,
        "havdalah_entity_id": None,
        "show_alarms": True,
        "alarm_entity_ids": None,
        "custom_widgets": [],
    },
    "home_layout": {
        "show_activity_overview": True,
        "activity_position": "end",
        "activity_width": 300,
        "activity_scale": 1.0,
        "info_scale": 1.0,
        "info_alignment": "start",
        "activity_categories": ["light", "switch", "climate", "cover"],
        "info_order": ["weather", "parasha", "candle", "havdalah"],
        "section_order": ["overview", "navigation", "devices"],
        "overview_style": "dashboard",
        "activity_layout": "grid",
        "clock_scale": 1.0,
        "overview_padding": 18,
        "info_columns": 2,
        "info_canvas_direction": "auto",
        "info_canvas_rows": 3,
        "info_canvas_gap": 10,
        "info_widgets": [
            {"id": "clock", "type": "clock", "column": 1, "row": 1, "width": 4, "height": 2, "align": "right", "scale": 1.0, "visible": True, "order": 1},
            {"id": "weather", "type": "weather", "column": 5, "row": 1, "width": 2, "height": 1, "align": "right", "scale": 1.0, "visible": True, "order": 2},
            {"id": "parasha", "type": "parasha", "column": 7, "row": 1, "width": 2, "height": 1, "align": "right", "scale": 1.0, "visible": True, "order": 3},
            {"id": "candle", "type": "candle", "column": 5, "row": 2, "width": 2, "height": 1, "align": "right", "scale": 1.0, "visible": True, "order": 4},
            {"id": "havdalah", "type": "havdalah", "column": 7, "row": 2, "width": 2, "height": 1, "align": "right", "scale": 1.0, "visible": True, "order": 5},
            {"id": "alarms", "type": "alarms", "column": 1, "row": 3, "width": 8, "height": 1, "align": "right", "scale": 1.0, "visible": True, "order": 6},
        ],
        "show_navigation": True,
        "home_card_width": 220,
        "home_card_width_mobile": 210,
        "category_width": 102,
        "desktop_overview_min": 340,
        "desktop_devices_height": 240,
        "mobile_overview_min": 240,
        "mobile_devices_height": 190,
        "section_gap": 10,
    },
    "floor_navigation": {
        "remember_expansion": True,
        "default_collapsed": True,
    },
    "room_defaults": {
        "layout_preset": "deck",
        "show_image": True,
        "show_temperature": True,
        "show_info": True,
        "controls_position": "bottom",
        "hero_size": 42,
        "controls_size": 58,
        "hero_widget_scale": 1.0,
        "control_card_width": 195,
        "hero_camera": "auto",
        "hero_camera_size": 34,
        "mobile_hero_size": 38,
        "mobile_control_card_width": 160,
        "hero_content_alignment": "start",
        "hero_overlay": 58,
        "control_gap": 8,
    },
    "background_source": "automatic",
    "global_background": "",
    "manual_backgrounds": {},
    "media_backgrounds": {},
    "area_domain_filters": {},
    "area_overrides": {},
    "entity_overrides": {},
    "area_backgrounds": True,
    "hidden_entities": [],
    "hidden_areas": [],
    "policies": [],
}

SUPPORTED_DOMAINS = {
    "alarm_control_panel",
    "camera",
    "climate",
    "cover",
    "light",
    "media_player",
    "switch",
}

